# ifeq ($(MODULE),)
#     $(error export MODULE before starting tests: example export MODULE=gpio   )
# endif

# ifeq ($(TEST),)
#     $(error export TEST before starting tests: example export TEST=gpio_TS_001   )
# endif

include UserConfig.mk

include $(DEBUGER).mk