MODULE := gpio
TEST   := gpio_TS_001
DEBUGER:= JLINK
# DEBUGER:= STLINK
JLINK_PATH := C:\Tool\Jlink\JLink
TARGET_DEVICE := STM32F407VG
INTERFACE := JTAG
OZONE_PATH := C:/Program Files/SEGGER/Ozone
